/**
 * Index Generator
 * Generates index files with barrel exports
 */

import type { GeneratedRepository } from '../../types/generator.types';

/**
 * Generates an index file that exports all repositories
 *
 * @param repositories - Array of generated repositories
 * @returns Index file content
 */
export function generateIndexFile(repositories: GeneratedRepository[]): string {
  const lines: string[] = [];

  // File header
  lines.push('/**');
  lines.push(' * Generated Repositories (Auto-generated)');
  lines.push(' *');
  lines.push(' * This file was automatically generated from the OpenAPI specification.');
  lines.push(' * Do not edit this file manually as changes will be overwritten.');
  lines.push(' *');
  lines.push(` * Generated: ${new Date().toISOString()}`);
  lines.push(' */');
  lines.push('');

  // Sort repositories by name for consistent output
  const sortedRepos = [...repositories].sort((a, b) =>
    a.resourceName.localeCompare(b.resourceName)
  );

  // Generate exports for each repository
  for (const repo of sortedRepos) {
    // Export class and interface
    lines.push(
      `export { ${repo.className}, type ${repo.interfaceName} } from './${repo.fileName.replace('.ts', '')}';`
    );
  }

  lines.push('');

  // Re-export all types from each repository
  lines.push('// Re-export all types');
  for (const repo of sortedRepos) {
    lines.push(`export * from './${repo.fileName.replace('.ts', '')}';`);
  }

  return lines.join('\n');
}

/**
 * Generates a README file for generated repositories
 *
 * @param repositories - Array of generated repositories
 * @returns README content
 */
export function generateReadme(repositories: GeneratedRepository[]): string {
  const lines: string[] = [];

  lines.push('# Generated Repositories');
  lines.push('');
  lines.push(
    'This directory contains auto-generated repository classes from your OpenAPI specification.'
  );
  lines.push('');
  lines.push('## ⚠️ Important');
  lines.push('');
  lines.push(
    '**Do not edit these files manually!** They are auto-generated and will be overwritten.'
  );
  lines.push('');
  lines.push('## Usage');
  lines.push('');
  lines.push('```typescript');
  lines.push("import { FetchApiClient } from 'velos-ts/runtime';");

  if (repositories.length > 0) {
    const firstRepo = repositories[0];
    if (firstRepo) {
      lines.push(`import { ${firstRepo.className} } from './repositories';`);
      lines.push('');
      lines.push('// Create API client');
      lines.push('const apiClient = new FetchApiClient({');
      lines.push("  baseUrl: 'https://api.example.com',");
      lines.push('  auth: () => getAuthToken(),');
      lines.push('});');
      lines.push('');
      lines.push('// Create repository');
      lines.push(`const ${firstRepo.resourceKey}Repo = new ${firstRepo.className}(apiClient);`);
      lines.push('');
      lines.push('// Use repository');
      lines.push(`const result = await ${firstRepo.resourceKey}Repo.someMethod();`);
      lines.push('if (result.success) {');
      lines.push('  console.log(result.data);');
      lines.push('} else {');
      lines.push('  console.error(result.error);');
      lines.push('}');
    }
  }

  lines.push('```');
  lines.push('');
  lines.push('## Generated Repositories');
  lines.push('');

  for (const repo of repositories) {
    lines.push(`### ${repo.className}`);
    lines.push('');
    lines.push(`- **File**: \`${repo.fileName}\``);
    lines.push(`- **Interface**: \`${repo.interfaceName}\``);
    lines.push(`- **Operations**: ${repo.methods.length}`);
    lines.push('');
  }

  lines.push('## Regeneration');
  lines.push('');
  lines.push('To regenerate these files:');
  lines.push('');
  lines.push('```bash');
  lines.push('npm run generate:repos');
  lines.push('```');
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push(`*Last generated: ${new Date().toISOString()}*`);

  return lines.join('\n');
}

/**
 * Generates a summary of what was generated
 *
 * @param repositories - Array of generated repositories
 * @returns Summary text
 */
export function generateSummary(repositories: GeneratedRepository[]): string {
  const totalMethods = repositories.reduce((sum, repo) => sum + repo.methods.length, 0);
  const totalTypes = repositories.reduce((sum, repo) => sum + repo.importedTypes.length, 0);

  const lines: string[] = [];
  lines.push('Generation Summary');
  lines.push('==================');
  lines.push('');
  lines.push(`Total Repositories: ${repositories.length}`);
  lines.push(`Total Methods: ${totalMethods}`);
  lines.push(`Total Types: ${totalTypes}`);
  lines.push('');
  lines.push('Generated Files:');

  for (const repo of repositories) {
    lines.push(`  - ${repo.fileName} (${repo.methods.length} methods)`);
  }

  return lines.join('\n');
}
