/**
 * Repository Generator
 * Main generator that orchestrates repository file generation
 */

import type { OpenAPISpec } from '../../types/openapi.types';
import type { ResourceGroup, GeneratedRepository } from '../../types/generator.types';
import type { GeneratorConfig } from '../../types/config.types';
import { collectUsedSchemas, collectQueryParamTypes } from '../analyzer/type-analyzer';
import { generateImports } from './import-generator';
import { generateAllTypes } from './type-alias-generator';
import { generateInterface, getInterfaceName, getClassName } from './interface-generator';
import { generateAllMethods } from './method-generator';
import { toKebabCase } from '../../utils/string-utils';

/**
 * Generates a complete repository file for a resource
 *
 * @param resource - Resource group
 * @param config - Generator configuration
 * @param spec - OpenAPI specification
 * @returns Generated repository information
 */
export function generateRepository(
  resource: ResourceGroup,
  config: GeneratorConfig,
  spec: OpenAPISpec
): GeneratedRepository {
  const className = getClassName(resource.name);
  const interfaceName = getInterfaceName(resource.name);

  // Analyze types
  const usedSchemas = collectUsedSchemas(resource, spec);
  const queryTypes = collectQueryParamTypes(resource);

  // Generate file sections
  const fileHeader = generateFileHeader(resource);
  const imports = generateImports(resource, config, usedSchemas);
  const types = generateAllTypes(usedSchemas, queryTypes, config);
  const interfaceCode = generateInterface(resource, interfaceName, spec);
  const classCode = generateClass(resource, className, interfaceName, spec);

  // Combine all sections
  const content = [fileHeader, imports, types, interfaceCode, classCode]
    .filter(Boolean)
    .join('\n\n');

  // Determine file path
  const fileName = `${toKebabCase(resource.resourceKey)}.repository.ts`;
  const filePath = `${config.outputDir}/${fileName}`;

  // Extract imported types
  const importedTypes = Array.from(usedSchemas);

  // Generate method metadata
  const methods = resource.operations.map((op) => ({
    name: op.operationId,
    signature: { params: '', returnType: '', parameters: [], returnTypeInfo: {} as any },
    implementation: '',
    jsdoc: op.summary,
    httpMethod: op.method,
    endpoint: op.path,
    operationId: op.operationId,
  }));

  return {
    resourceName: resource.name,
    resourceKey: resource.resourceKey,
    fileName,
    filePath,
    content,
    className,
    interfaceName,
    importedTypes,
    methods,
    typeAliases: [],
  };
}

/**
 * Generates the file header comment
 *
 * @param resource - Resource group
 * @returns Header comment
 */
function generateFileHeader(resource: ResourceGroup): string {
  return `/**
 * ${resource.name} Repository (Auto-generated)
 *
 * This file was automatically generated from the OpenAPI specification.
 * Do not edit this file manually as changes will be overwritten.
 *
 * Base Path: ${resource.basePath}
 * Tag: ${resource.tag}
 * Generated: ${new Date().toISOString()}
 */`;
}

/**
 * Generates the repository class implementation
 *
 * @param resource - Resource group
 * @param className - Class name
 * @param interfaceName - Interface name
 * @param spec - OpenAPI specification
 * @returns Class implementation as string
 */
function generateClass(
  resource: ResourceGroup,
  className: string,
  interfaceName: string,
  spec: OpenAPISpec
): string {
  const methods = generateAllMethods(resource, spec);
  const entityType = resource.primaryEntityType || 'unknown';

  const lines: string[] = [];

  // JSDoc comment
  lines.push('/**');
  lines.push(` * ${resource.name} Repository Implementation`);
  lines.push(' *');
  lines.push(` * Concrete implementation of ${interfaceName}.`);
  lines.push(` * Provides type-safe access to ${resource.name} API endpoints.`);
  lines.push(' *');
  lines.push(` * @class ${className}`);
  lines.push(` * @extends {BaseRepository<${entityType}>}`);
  lines.push(` * @implements {${interfaceName}}`);
  lines.push(' */');

  // Class declaration
  lines.push(
    `export class ${className} extends BaseRepository<${entityType}> implements ${interfaceName} {`
  );

  // Endpoint property
  lines.push('  /**');
  lines.push('   * API endpoint base path');
  lines.push('   */');
  lines.push(`  protected readonly endpoint = '${resource.basePath}';`);
  lines.push('');

  // Constructor
  lines.push('  /**');
  lines.push(`   * Creates a new ${className} instance`);
  lines.push('   *');
  lines.push('   * @param apiClient - API client for HTTP requests');
  lines.push('   */');
  lines.push('  constructor(apiClient: ApiClient) {');
  lines.push('    super(apiClient);');
  lines.push('  }');
  lines.push('');

  // Methods
  lines.push(methods.join('\n\n'));

  // Close class
  lines.push('}');

  return lines.join('\n');
}

/**
 * Generates repositories for all resources
 *
 * @param resources - Array of resource groups
 * @param config - Generator configuration
 * @param spec - OpenAPI specification
 * @returns Array of generated repositories
 */
export function generateAllRepositories(
  resources: ResourceGroup[],
  config: GeneratorConfig,
  spec: OpenAPISpec
): GeneratedRepository[] {
  return resources.map((resource) => generateRepository(resource, config, spec));
}
